mewna/catnip

- src/main/java/com/mewna/catnip/entity/Embed.java
- src/main/java/com/mewna/catnip/entity/EntityBuilder.java
- src/main/java/com/mewna/catnip/entity/Message.java
- src/main/java/com/mewna/catnip/rest/Rest.java
- src/main/java/com/mewna/catnip/rest/RestRequester.java
- src/main/java/com/mewna/catnip/shard/DispatchEmitter.java
- Message timestamps are now OffsetDateTime objects
- Fixed NullPointerException on missing headers
- Decoupled entity creation from event dispatching
- Added method to retrieve message by id
> Add Embed entity plus a few other improvements

- src/main/java/com/mewna/catnip/entity/EntityBuilder.java
- src/main/java/com/mewna/catnip/entity/Member.java
- src/main/java/com/mewna/catnip/entity/Permission.java
- src/main/java/com/mewna/catnip/rest/ResponsePayload.java
- src/main/java/com/mewna/catnip/rest/Rest.java
- src/main/java/com/mewna/catnip/rest/RestRequester.java
- src/test/java/com/mewna/catnip/permission/BitwiseTest.java
Also:
- Changed Permission#toList to Permission#toSet
- Added method to retrieve users
- Added method to retrieve guild roles
> Allow requesting from endpoints that return arrays

- src/main/java/com/mewna/catnip/entity/Embed.java
- src/main/java/com/mewna/catnip/entity/Entity.java
- src/main/java/com/mewna/catnip/entity/Member.java
- src/main/java/com/mewna/catnip/entity/Message.java
- src/main/java/com/mewna/catnip/entity/Snowflake.java
- src/main/java/com/mewna/catnip/entity/builder/EmbedBuilder.java
- src/main/java/com/mewna/catnip/entity/builder/MessageBuilder.java
- src/main/java/com/mewna/catnip/entity/impl/EmbedImpl.java
- src/main/java/com/mewna/catnip/entity/impl/EntityBuilder.java
- src/main/java/com/mewna/catnip/entity/impl/MemberImpl.java
- src/main/java/com/mewna/catnip/entity/impl/MessageImpl.java
- src/main/java/com/mewna/catnip/entity/impl/RequiresCatnip.java
- src/main/java/com/mewna/catnip/entity/impl/RoleImpl.java
- src/main/java/com/mewna/catnip/entity/impl/UserImpl.java
- src/main/java/com/mewna/catnip/internal/CatnipImpl.java
- src/main/java/com/mewna/catnip/rest/handler/RestChannel.java
- src/main/java/com/mewna/catnip/rest/handler/RestHandler.java
- src/main/java/com/mewna/catnip/shard/DispatchEmitter.java
- src/main/java/com/mewna/catnip/util/JsonPojoCodec.java
- src/main/java/com/mewna/catnip/util/Utils.java
- Added Snowflake and Entity interfaces
- Separated Embed into interface and implementation
- Entities now get a Catnip instance when deserializing
> Entity changes

- src/main/java/com/mewna/catnip/internal/ratelimit/MemoryRatelimiter.java
- src/test/java/com/mewna/catnip/internal/ratelimit/MemoryRatelimiterTest.java
Rework rate limiter
- Now resets if the window passed, not set up the reset when the permits have been used up
- Now resets based on the current time, not the last reset time :v
> Ratelimiter fixes

- pom.xml
- src/main/java/com/mewna/catnip/Catnip.java
- src/main/java/com/mewna/catnip/extension/AbstractExtension.java
- src/main/java/com/mewna/catnip/extension/Extension.java
- src/main/java/com/mewna/catnip/extension/manager/DefaultExtensionManager.java
- src/main/java/com/mewna/catnip/extension/manager/ExtensionManager.java
- src/main/java/com/mewna/catnip/internal/CatnipImpl.java
- src/main/java/com/mewna/catnip/rest/RestRequester.java
- src/main/java/com/mewna/catnip/shard/CatnipShard.java
> Add basic support for extensions

- pom.xml
- src/main/java/com/mewna/catnip/rest/ResponsePayload.java
- src/main/java/com/mewna/catnip/rest/RestRequester.java
- src/main/java/com/mewna/catnip/shard/manager/DefaultShardManager.java
> Use OkHTTP for REST

- src/main/java/com/mewna/catnip/rest/handler/RestChannel.java
adds support for all the channel routes from #3
> add support for channel routes

- src/main/java/com/mewna/catnip/extension/AbstractExtension.java
- src/main/java/com/mewna/catnip/extension/Extension.java
- src/main/java/com/mewna/catnip/extension/hook/CatnipHook.java
- src/main/java/com/mewna/catnip/extension/manager/DefaultExtensionManager.java
- src/main/java/com/mewna/catnip/extension/manager/ExtensionManager.java
- src/main/java/com/mewna/catnip/rest/RestRequester.java
- src/main/java/com/mewna/catnip/shard/CatnipShard.java
Allow hooking into some library internals for memes:tm: if you really want it. Includes nice big warning against doing it.
> Add the super-meme hook functionality

- src/main/java/com/mewna/catnip/entity/guild/audit/ActionType.java
- src/main/java/com/mewna/catnip/entity/guild/audit/AuditLog.java
- src/main/java/com/mewna/catnip/entity/guild/audit/AuditLogChange.java
- src/main/java/com/mewna/catnip/entity/guild/audit/AuditLogEntry.java
- src/main/java/com/mewna/catnip/entity/guild/audit/MemberPruneInfo.java
- src/main/java/com/mewna/catnip/entity/guild/audit/MessageDeleteInfo.java
- src/main/java/com/mewna/catnip/entity/guild/audit/OptionalEntryInfo.java
- src/main/java/com/mewna/catnip/entity/guild/audit/OverrideUpdateInfo.java
- src/main/java/com/mewna/catnip/entity/impl/AuditLogChangeImpl.java
- src/main/java/com/mewna/catnip/entity/impl/AuditLogEntryImpl.java
- src/main/java/com/mewna/catnip/entity/impl/AuditLogImpl.java
- src/main/java/com/mewna/catnip/entity/impl/EntityBuilder.java
- src/main/java/com/mewna/catnip/entity/impl/MemberPruneInfoImpl.java
- src/main/java/com/mewna/catnip/entity/impl/MessageDeleteInfoImpl.java
- src/main/java/com/mewna/catnip/entity/impl/OverrideUpdateInfoImpl.java
- src/main/java/com/mewna/catnip/rest/Routes.java
- src/main/java/com/mewna/catnip/rest/handler/RestGuild.java
adds support for all audit log stuff (that i know of)
**only partially tested (everything besides `options` and `changes`)**
fixed a small typo in the route path too
> audit logs

- src/main/java/com/mewna/catnip/entity/impl/EntityBuilder.java
Fixes errors being thrown when fetching a message with reactions
> fix reaction parsing

- src/main/java/com/mewna/catnip/CatnipOptions.java
- src/main/java/com/mewna/catnip/internal/CatnipImpl.java
- src/main/java/com/mewna/catnip/rest/RestRequester.java
- src/main/java/com/mewna/catnip/rest/bucket/BucketBackend.java
- src/main/java/com/mewna/catnip/rest/bucket/MemoryBucketBackend.java
> Rest buckets

- src/main/java/com/mewna/catnip/entity/impl/EntityBuilder.java
- src/main/java/com/mewna/catnip/entity/impl/MessageEmbedUpdateImpl.java
- src/main/java/com/mewna/catnip/entity/message/MessageEmbedUpdate.java
- src/main/java/com/mewna/catnip/shard/DiscordEvent.java
- src/main/java/com/mewna/catnip/shard/DispatchEmitter.java
Fixes the processing bug in MESSAGE_UPDATE when Discord resolves embeds
> Special-case message embed updates

- src/main/java/com/mewna/catnip/entity/guild/Member.java
- src/main/java/com/mewna/catnip/entity/impl/EntityBuilder.java
Fixes the Member#joinedAt bug in GUILD_MEMBER_REMOVE
> Nullable member fields

- src/main/java/com/mewna/catnip/entity/channel/MessageChannel.java
- src/main/java/com/mewna/catnip/entity/message/MessageOptions.java
- src/main/java/com/mewna/catnip/rest/RestRequester.java
- src/main/java/com/mewna/catnip/rest/handler/RestChannel.java
> multiple file support and some convenience methods

- src/main/java/com/mewna/catnip/Catnip.java
- src/main/java/com/mewna/catnip/CatnipOptions.java
- src/main/java/com/mewna/catnip/cache/MemoryEntityCache.java
- src/main/java/com/mewna/catnip/internal/CatnipImpl.java
- src/main/java/com/mewna/catnip/shard/CatnipShard.java
- src/main/java/com/mewna/catnip/shard/event/CachingBuffer.java
- src/main/java/com/mewna/catnip/shard/manager/DefaultShardManager.java
> Real member chunking support

- src/main/java/com/mewna/catnip/Catnip.java
- src/main/java/com/mewna/catnip/CatnipOptions.java
- src/main/java/com/mewna/catnip/cache/EntityCache.java
- src/main/java/com/mewna/catnip/cache/NoopEntityCache.java
- src/main/java/com/mewna/catnip/entity/builder/EmbedBuilder.java
- src/main/java/com/mewna/catnip/entity/builder/MessageBuilder.java
- src/main/java/com/mewna/catnip/entity/builder/PresenceBuilder.java
- src/main/java/com/mewna/catnip/entity/impl/PresenceImpl.java
- src/main/java/com/mewna/catnip/entity/user/Presence.java
- src/main/java/com/mewna/catnip/internal/CatnipImpl.java
- src/main/java/com/mewna/catnip/shard/CatnipShard.java
- src/main/java/com/mewna/catnip/shard/manager/DefaultShardManager.java
adds presence update support + some convenience methods inside the `Catnip` interface
note: i had to pull off a minor quirky thing which is presence updates being sent on random shards, as it's impossible to know which specific shard to use from just using the `Catnip` interface. it does work and is tested tho so 👌
> presence updates

- pom.xml
- src/main/java/com/mewna/catnip/Catnip.java
- src/main/java/com/mewna/catnip/cache/MemoryEntityCache.java
- src/main/java/com/mewna/catnip/entity/guild/Guild.java
- src/main/java/com/mewna/catnip/entity/impl/EntityBuilder.java
- src/main/java/com/mewna/catnip/entity/impl/GuildImpl.java
- src/main/java/com/mewna/catnip/internal/CatnipImpl.java
- src/main/java/com/mewna/catnip/shard/CatnipShard.java
- src/main/java/com/mewna/catnip/shard/DiscordEvent.java
- src/main/java/com/mewna/catnip/shard/DispatchEmitter.java
- src/main/java/com/mewna/catnip/shard/event/CachingBuffer.java
> Update caching and other things

- src/main/java/com/mewna/catnip/entity/GuildEmbed.java
- src/main/java/com/mewna/catnip/entity/guild/Role.java
- src/main/java/com/mewna/catnip/entity/impl/EntityBuilder.java
- src/main/java/com/mewna/catnip/entity/impl/GuildEmbedImpl.java
- src/main/java/com/mewna/catnip/internal/CatnipImpl.java
- src/main/java/com/mewna/catnip/rest/RestRequester.java
- src/main/java/com/mewna/catnip/rest/guild/ChannelData.java
- src/main/java/com/mewna/catnip/rest/guild/GuildData.java
- src/main/java/com/mewna/catnip/rest/guild/MemberData.java
- src/main/java/com/mewna/catnip/rest/guild/PositionUpdater.java
- src/main/java/com/mewna/catnip/rest/handler/RestChannel.java
- src/main/java/com/mewna/catnip/rest/handler/RestEmoji.java
- src/main/java/com/mewna/catnip/rest/handler/RestGuild.java
- src/main/java/com/mewna/catnip/rest/handler/RestInvite.java
- src/main/java/com/mewna/catnip/rest/handler/RestUser.java
- src/main/java/com/mewna/catnip/rest/handler/RestVoice.java
- src/main/java/com/mewna/catnip/rest/handler/RestWebhook.java
fully closes #3 👏 👍 
each added route has been tested to a decent degree too
> fix a few bugs + support for all routes

- src/main/java/com/mewna/catnip/internal/CatnipImpl.java
- src/main/java/com/mewna/catnip/shard/CatnipShard.java
- src/main/java/com/mewna/catnip/util/BufferOutputStream.java
TODO: possibly add a maximum size for the buffers and clear if they pass that size?
> Reuse buffers in the websocket connection to lower GC pressure

- src/main/java/com/mewna/catnip/Catnip.java
- src/main/java/com/mewna/catnip/entity/channel/VoiceChannel.java
- src/main/java/com/mewna/catnip/entity/guild/Guild.java
- src/main/java/com/mewna/catnip/internal/CatnipImpl.java
- src/main/java/com/mewna/catnip/shard/CatnipShard.java
also moved some implementations from Catnip to CatnipImpl
> Voice channel join/leave

- src/main/java/com/mewna/catnip/entity/impl/EntityBuilder.java
note to self stop working on serious stuff at 2 am
> oopsie woopsie i made a fucky wucky

- src/main/java/com/mewna/catnip/cache/EntityCache.java
- src/main/java/com/mewna/catnip/cache/MemoryEntityCache.java
- src/main/java/com/mewna/catnip/cache/NoopEntityCache.java
- src/main/java/com/mewna/catnip/cache/view/CacheView.java
- src/main/java/com/mewna/catnip/cache/view/CompositeCacheView.java
- src/main/java/com/mewna/catnip/cache/view/CompositeNamedCacheView.java
- src/main/java/com/mewna/catnip/cache/view/DefaultCacheView.java
- src/main/java/com/mewna/catnip/cache/view/DefaultNamedCacheView.java
- src/main/java/com/mewna/catnip/cache/view/EmptyCacheView.java
- src/main/java/com/mewna/catnip/cache/view/EmptyNamedCacheView.java
- src/main/java/com/mewna/catnip/cache/view/NamedCacheView.java
- src/main/java/com/mewna/catnip/entity/impl/PresenceUpdateImpl.java
- src/main/java/com/mewna/catnip/entity/message/Message.java
- src/main/java/com/mewna/catnip/entity/user/PresenceUpdate.java
also added missing copyright headers
> Store IDs as longs in the cache

- src/main/java/com/mewna/catnip/Catnip.java
- src/main/java/com/mewna/catnip/CatnipOptions.java
- src/main/java/com/mewna/catnip/entity/channel/Channel.java
- src/main/java/com/mewna/catnip/entity/channel/GuildChannel.java
- src/main/java/com/mewna/catnip/entity/channel/MessageChannel.java
- src/main/java/com/mewna/catnip/entity/channel/TextChannel.java
- src/main/java/com/mewna/catnip/entity/channel/Webhook.java
- src/main/java/com/mewna/catnip/entity/guild/Guild.java
- src/main/java/com/mewna/catnip/entity/guild/Invite.java
- src/main/java/com/mewna/catnip/entity/guild/Member.java
- src/main/java/com/mewna/catnip/entity/guild/PermissionOverride.java
- src/main/java/com/mewna/catnip/entity/guild/Role.java
- src/main/java/com/mewna/catnip/entity/impl/EntityBuilder.java
- src/main/java/com/mewna/catnip/entity/impl/PermissionOverrideImpl.java
- src/main/java/com/mewna/catnip/entity/impl/RoleImpl.java
- src/main/java/com/mewna/catnip/entity/message/Message.java
- src/main/java/com/mewna/catnip/entity/util/Permission.java
- src/main/java/com/mewna/catnip/internal/CatnipImpl.java
- src/main/java/com/mewna/catnip/util/MissingPermissionException.java
- src/main/java/com/mewna/catnip/util/PermissionUtil.java
- Calculate permissions
- Enforce permission checks
> Permission stuff

- src/main/java/com/mewna/catnip/Catnip.java
- src/main/java/com/mewna/catnip/extension/AbstractExtension.java
- src/main/java/com/mewna/catnip/extension/Extension.java
- src/main/java/com/mewna/catnip/extension/manager/DefaultExtensionManager.java
- src/main/java/com/mewna/catnip/extension/manager/ExtensionManager.java
fix small doc issue on Catnip
use the generic type in the return value of ExtensionManager#matchingExtensions and ExtensionManager#extension
> add Extension#on (fixes #135)

- src/main/java/com/mewna/catnip/cache/MemoryEntityCache.java
- src/main/java/com/mewna/catnip/cache/view/CacheView.java
- src/main/java/com/mewna/catnip/cache/view/CompositeCacheView.java
- src/main/java/com/mewna/catnip/cache/view/CompositeNamedCacheView.java
- src/main/java/com/mewna/catnip/cache/view/DefaultCacheView.java
- src/main/java/com/mewna/catnip/cache/view/DefaultNamedCacheView.java
- src/main/java/com/mewna/catnip/cache/view/EmptyCacheView.java
- src/main/java/com/mewna/catnip/cache/view/EmptyNamedCacheView.java
- src/main/java/com/mewna/catnip/cache/view/MutableCacheView.java
- src/main/java/com/mewna/catnip/cache/view/MutableNamedCacheView.java
- src/main/java/com/mewna/catnip/cache/view/NamedCacheView.java
- src/test/java/com/mewna/catnip/cache/view/CompositeCacheViewTests.java
- src/test/java/com/mewna/catnip/cache/view/DefaultCacheViewTests.java
- Add MutableCacheView/MutableNamedCacheView interfaces
- Allow users to change the cache view implementations used by MemoryEntityCache
- Add CacheView#count
- Add overloads in NamedCacheView for specifying a custom result collection type
- Add missing jsr305 annotations
> More cache improvements

- src/main/java/com/mewna/catnip/rest/handler/RestChannel.java
- src/main/java/com/mewna/catnip/rest/handler/RestEmoji.java
- src/main/java/com/mewna/catnip/rest/handler/RestGuild.java
- src/main/java/com/mewna/catnip/rest/handler/RestInvite.java
- src/main/java/com/mewna/catnip/rest/handler/RestUser.java
- src/main/java/com/mewna/catnip/rest/handler/RestVoice.java
- src/main/java/com/mewna/catnip/rest/handler/RestWebhook.java
> Add raw rest methods

- src/main/java/com/mewna/catnip/entity/guild/Member.java
**still needs to be tested**
would maybe be a bad idea if you merged right now 👀
> add color method

- .idea/codeStyles/Project.xml
- src/main/java/com/mewna/catnip/rest/handler/RestChannel.java
- src/main/java/com/mewna/catnip/rest/handler/RestGuild.java
- src/main/java/com/mewna/catnip/rest/handler/RestUser.java
- src/main/java/com/mewna/catnip/util/QueryStringBuilder.java
This references issue #52, and should provide a working implementation, ~~of course provided by @natanbc~~
> Added QueryStringBuilder

- src/main/java/com/mewna/catnip/entity/builder/EmbedBuilder.java
**not** tested, will do that tomorrow
posted it early to get feedback quicker
> add embed timestamps

- src/main/java/com/mewna/catnip/cache/MemoryEntityCache.java
:clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap::clap:
> Fix entities not being cached

- src/main/java/com/mewna/catnip/entity/impl/EntityBuilder.java
> patch timestamps not being added to jsonobject

- pom.xml
- src/main/java/com/mewna/catnip/Catnip.java
- src/main/java/com/mewna/catnip/internal/CatnipImpl.java
- src/main/java/com/mewna/catnip/rest/RestRequester.java
- src/main/java/com/mewna/catnip/shard/manager/AbstractShardManager.java
- src/main/java/com/mewna/catnip/util/SafeVertxCompletableFuture.java
> disallow blocking event loop, add Catnip#catnipAsync, only print codec warning once

- src/main/java/com/mewna/catnip/entity/impl/EntityBuilder.java
- src/main/java/com/mewna/catnip/entity/impl/PresenceImpl.java
- src/main/java/com/mewna/catnip/entity/impl/PresenceUpdateImpl.java
- src/main/java/com/mewna/catnip/entity/user/Presence.java
- src/main/java/com/mewna/catnip/entity/user/PresenceUpdate.java
Just removing that one bit of uncertainty with if they are on desktop or not.
Feel free to suggest edits if I missed anything, or broke something.
> Added desktopStatus in Presence and PresenceUpdate and implementations

- README.md
Discord4J v3 is encouraged and handles ratelimits for you.
> Update README to correct info

- src/main/java/com/mewna/catnip/entity/channel/GuildChannel.java
- src/main/java/com/mewna/catnip/entity/channel/Webhook.java
- src/main/java/com/mewna/catnip/entity/channel/WebhooksUpdate.java
- src/main/java/com/mewna/catnip/entity/guild/EmojiUpdate.java
- src/main/java/com/mewna/catnip/entity/guild/GatewayGuildBan.java
- src/main/java/com/mewna/catnip/entity/guild/Guild.java
- src/main/java/com/mewna/catnip/entity/guild/GuildEntity.java
- src/main/java/com/mewna/catnip/entity/guild/Member.java
- src/main/java/com/mewna/catnip/entity/guild/PartialMember.java
- src/main/java/com/mewna/catnip/entity/guild/PartialRole.java
- src/main/java/com/mewna/catnip/entity/guild/Role.java
- src/main/java/com/mewna/catnip/entity/misc/Emoji.java
- src/main/java/com/mewna/catnip/entity/user/PresenceUpdate.java
- src/main/java/com/mewna/catnip/entity/user/User.java
- src/main/java/com/mewna/catnip/entity/voice/VoiceServerUpdate.java
Adds methods such as Member#effectiveName, Guild#selfMember and Guild#owner, also centralizes all "long guildIdAsLong()" methods in GuildEntity and provides GuildEntity#guild method.
> GuildEntity and useful methods

- src/main/java/com/mewna/catnip/shard/buffer/CachingBuffer.java
- src/main/java/com/mewna/catnip/util/JsonUtil.java
fix immutable set being returned by JsonUtil.toMutableSet
avoid creating an useless copy in CachingBuffer
only send chunk requests if member chunking is enabled
> change some stuff

- pom.xml
- src/main/java/com/mewna/catnip/internal/CatnipImpl.java
- src/main/java/com/mewna/catnip/shard/CatnipShard.java
- src/main/java/com/mewna/catnip/shard/LifecycleEvent.java
- src/main/java/com/mewna/catnip/shard/ShardAddress.java
- src/main/java/com/mewna/catnip/shard/ShardConnectState.java
- src/main/java/com/mewna/catnip/shard/ShardControlMessage.java
- src/main/java/com/mewna/catnip/shard/manager/AbstractShardManager.java
- src/main/java/com/mewna/catnip/shard/manager/DefaultShardManager.java
- src/main/java/com/mewna/catnip/shard/manager/ShardCondition.java
> Rewrite shard management

- src/main/java/com/mewna/catnip/entity/builder/EmbedBuilder.java
**N O T** tested but the logic is very easy and should definitely work and has been reviewed.
looking for any possible changes, especially to the documentation.
> replaceAtIndex addition + docs for it

- src/main/java/com/mewna/catnip/entity/channel/Webhook.java
Implement the execution of Webhook objects
> Webhook execution implementated

- src/main/java/com/mewna/catnip/entity/impl/VoiceStateImpl.java
- src/main/java/com/mewna/catnip/entity/user/VoiceState.java
Added extra, utility methods to `VoiceState` class.
> VoiceState utility methods

- pom.xml
- src/main/java/com/mewna/catnip/entity/channel/Webhook.java
- src/main/java/com/mewna/catnip/entity/guild/Invite.java
- src/main/java/com/mewna/catnip/entity/guild/UnavailableGuild.java
- src/main/java/com/mewna/catnip/entity/guild/audit/AuditLogChange.java
- src/main/java/com/mewna/catnip/entity/guild/audit/OptionalEntryInfo.java
- src/main/java/com/mewna/catnip/entity/impl/EmbedImpl.java
- src/main/java/com/mewna/catnip/entity/impl/InviteImpl.java
- src/main/java/com/mewna/catnip/entity/impl/MessageImpl.java
- src/main/java/com/mewna/catnip/entity/impl/PresenceImpl.java
- src/main/java/com/mewna/catnip/entity/misc/ApplicationOwner.java
- src/main/java/com/mewna/catnip/entity/misc/Emoji.java
- src/main/java/com/mewna/catnip/entity/user/Presence.java
- src/main/java/com/mewna/catnip/util/JsonPojoCodec.java
- src/test/java/com/mewna/catnip/entity/CodecTest.java
- src/test/resources/logback-test.xml
Finally done! (there are two more TODOs left but those are more nice to have)
Also closes #219
> Add codec test

- src/main/java/com/mewna/catnip/Catnip.java
- src/main/java/com/mewna/catnip/internal/CatnipImpl.java
Is an atomic reference the best thing to use to store the client id? Or should I just use a normal old non-final field?
> Add clientId storing

- src/main/java/com/mewna/catnip/rest/handler/RestUser.java
> Fix leaving guild

- src/main/java/com/mewna/catnip/rest/handler/RestGuild.java
Add ability to not provide a reason, fail if days are above 7 and fix a
typo.
Fixes #264
> Fix createGuildBan

- src/main/java/com/mewna/catnip/shard/CatnipShard.java
- src/main/java/com/mewna/catnip/shard/ShardConnectState.java
- src/main/java/com/mewna/catnip/shard/manager/DefaultShardManager.java
- src/main/java/com/mewna/catnip/util/task/QueueTask.java
50 shards connected successfully without catnip getting on :fire:
> Fix shard queueing and add missing replies

- src/main/java/com/mewna/catnip/shard/CatnipShard.java
My changes to queue code caused that, thankfully not much has been broken :eyes:
>  Fix presence and voice state updates 

- src/main/java/com/mewna/catnip/rest/requester/AbstractRequester.java
cc @natanbc, the comment block in AbstractRequester should be enough explanation to justify this
> Fix reaction ratelimits again

- src/main/java/com/mewna/catnip/rest/handler/RestChannel.java
Just so you can upload files on their own.
> Lone-file fix backport

- src/main/java/com/mewna/catnip/rest/handler/RestChannel.java
*clearly, I wasn't paying enough attention*
> Fixed tiny mistake regarding the 'Message' implementation of sendMessageRaw

- src/main/java/com/mewna/catnip/entity/guild/Member.java
- src/main/java/com/mewna/catnip/util/PermissionUtil.java
Made passing Catnip not required.
> Permission util update

- src/main/java/com/mewna/catnip/internal/CatnipImpl.java
> Fixed Lifecycle not having a codec registered

- src/main/java/com/mewna/catnip/Catnip.java
- src/main/java/com/mewna/catnip/CatnipOptions.java
- src/main/java/com/mewna/catnip/internal/CatnipImpl.java
- src/main/java/com/mewna/catnip/shard/buffer/CachingBuffer.java
Should hopefully help with some guilds getting "stuck." Inspired by https://github.com/DV8FromTheWorld/JDA/commit/caf8aae4de56b01bb476e77145abd7c15d392f19.
cc @natanbc
> Support member chunk re-requesting

- .gitignore
- pom.xml
> Run javadoc on delombok'd sources

- src/main/java/com/mewna/catnip/util/logging/DefaultLogAdapter.java
> StackWalker for Logger

- pom.xml
- src/main/java/com/mewna/catnip/CatnipOptions.java
- src/main/java/com/mewna/catnip/entity/message/MessageOptions.java
- src/main/java/com/mewna/catnip/extension/AbstractExtension.java
- src/main/java/com/mewna/catnip/extension/manager/DefaultExtensionManager.java
- src/main/java/com/mewna/catnip/internal/CatnipImpl.java
- src/main/java/com/mewna/catnip/rest/RestPayloadException.java
- src/main/java/com/mewna/catnip/rest/guild/MemberData.java
- src/main/java/com/mewna/catnip/rest/guild/PositionUpdater.java
- src/main/java/com/mewna/catnip/rest/handler/RestChannel.java
- src/main/java/com/mewna/catnip/rest/handler/RestEmoji.java
- src/main/java/com/mewna/catnip/rest/handler/RestGuild.java
- src/main/java/com/mewna/catnip/rest/handler/RestInvite.java
- src/main/java/com/mewna/catnip/rest/handler/RestUser.java
- src/main/java/com/mewna/catnip/rest/handler/RestVoice.java
- src/main/java/com/mewna/catnip/rest/handler/RestWebhook.java
- src/main/java/com/mewna/catnip/rest/requester/AbstractRequester.java
- src/main/java/com/mewna/catnip/shard/buffer/CachingBuffer.java
- src/main/java/com/mewna/catnip/shard/manager/DefaultShardManager.java
- src/main/java/com/mewna/catnip/util/MissingPermissionException.java
Replaces (and removes) Guava so we don't depend on Guava Immutable Collections anymore.
> [fuck-vertx] Replace Guava with Java 11's Immutable Collections

- src/main/java/com/mewna/catnip/entity/Entity.java
- src/main/java/com/mewna/catnip/internal/CatnipImpl.java
- src/main/java/com/mewna/catnip/util/JsonEntityCodec.java
- src/main/java/com/mewna/catnip/util/JsonUtil.java
- src/main/java/com/mewna/catnip/util/Utils.java
- src/test/java/com/mewna/catnip/entity/CodecTest.java
Partially deals with the issues in #318.
> De/stringify snowflakes in serialized entities/objects

- src/main/java/com/mewna/catnip/util/Utils.java
TL;DR you forgot to .find() it.
> Fix Webhook Parsing

- src/main/java/com/mewna/catnip/entity/user/Presence.java
Not supported by the gateway yet, but as we know Discord likes to break stuff (meanwhile adding a cool thing) https://github.com/DJScias/Discord-Datamining/commit/f83e634047127ea7b9d5e34e2d640a2f135be59b
> Add CUSTOM_STATUS activity type

- src/main/java/com/mewna/catnip/entity/impl/EntityBuilder.java
- src/main/java/com/mewna/catnip/entity/impl/TeamImpl.java
- src/main/java/com/mewna/catnip/entity/impl/TeamMemberImpl.java
- src/main/java/com/mewna/catnip/entity/misc/ApplicationInfo.java
- src/main/java/com/mewna/catnip/entity/misc/Team.java
- src/main/java/com/mewna/catnip/entity/misc/TeamMember.java
- src/main/java/com/mewna/catnip/util/CDNFormat.java
> Implement teams

- src/main/java/com/mewna/catnip/shard/CatnipShard.java
Should fix `java.lang.IllegalStateException: WebSocket is closed` memes
> Workaround for vert.x stupidness

- src/main/java/com/mewna/catnip/CatnipOptions.java
- src/main/java/com/mewna/catnip/shard/CatnipShard.java
See #346 discordapp/discord-api-docs#1016
> Add support for guild_subscriptions flag.

- src/main/java/com/mewna/catnip/shard/CatnipShard.java
- src/main/java/com/mewna/catnip/util/ReentrantLockWebSocket.java
> V2 reentrant ws

- src/main/java/com/mewna/catnip/Catnip.java
- src/main/java/com/mewna/catnip/CatnipOptions.java
- src/main/java/com/mewna/catnip/extension/AbstractExtension.java
- src/main/java/com/mewna/catnip/extension/Extension.java
- src/main/java/com/mewna/catnip/extension/manager/DefaultExtensionManager.java
- src/main/java/com/mewna/catnip/internal/CatnipImpl.java
- src/main/java/com/mewna/catnip/shard/event/DefaultDispatchManager.java
- src/main/java/com/mewna/catnip/shard/event/DispatchManager.java
- src/main/java/com/mewna/catnip/shard/event/MessageConsumer.java
- src/main/java/com/mewna/catnip/util/scheduler/AbstractTaskScheduler.java
- src/main/java/com/mewna/catnip/util/scheduler/RxTaskScheduler.java
- src/main/java/com/mewna/catnip/util/scheduler/TaskScheduler.java
- src/test/java/com/mewna/catnip/shard/event/DefaultDispatchManagerTest.java
- src/test/java/com/mewna/catnip/util/scheduler/RxTaskSchedulerTest.java
Local-brewed no-vertx DispatchManager.
> AruDiscord's attempt to kill vert.x

- src/main/java/com/mewna/catnip/Catnip.java
- src/main/java/com/mewna/catnip/CatnipOptions.java
- src/main/java/com/mewna/catnip/internal/CatnipImpl.java
- src/main/java/com/mewna/catnip/rest/requester/AbstractRequester.java
- src/main/java/com/mewna/catnip/shard/CatnipShardImpl.java
- src/main/java/com/mewna/catnip/util/rx/RxHelpers.java
- src/test/java/com/mewna/catnip/shard/event/DefaultDispatchManagerTest.java
- src/test/java/com/mewna/catnip/util/scheduler/RxTaskSchedulerTest.java
Reduce HTTP client / thread pool spamme
> V2 http thread pools

- src/main/java/com/mewna/catnip/entity/impl/EntityBuilder.java
- src/main/java/com/mewna/catnip/internal/CatnipImpl.java
> Enable users to input empty tokens on non-validation.

- src/main/java/com/mewna/catnip/Catnip.java
- src/main/java/com/mewna/catnip/rest/handler/RestWebhook.java
- src/main/java/com/mewna/catnip/shard/manager/ShardCondition.java
- Removed debug System.out.println
- Removed vert.x from docs
> Clean-up of forgotten stuff

- src/main/java/com/mewna/catnip/entity/impl/EntityBuilder.java
*Hopefully no more presence-related issues.*
> Added Activity Emoji to createActivity

- src/main/java/com/mewna/catnip/rest/requester/AbstractRequester.java
> Make AbstractRequester extensible

- src/main/java/com/mewna/catnip/entity/impl/EntityBuilder.java
- src/main/java/com/mewna/catnip/entity/impl/message/MessageImpl.java
- src/main/java/com/mewna/catnip/entity/message/Message.java
- src/main/java/com/mewna/catnip/entity/message/MessageOptions.java
- src/main/java/com/mewna/catnip/rest/handler/RestChannel.java
Closes #484.
See: https://github.com/discord/discord-api-docs/pull/2118
> feature: v8 message references

- src/main/java/com/mewna/catnip/entity/impl/EntityBuilder.java
- src/main/java/com/mewna/catnip/entity/impl/interaction/ApplicationCommandInteractionDataOptionImpl.java
- src/main/java/com/mewna/catnip/entity/interaction/ApplicationCommandInteractionDataOption.java
Hey Amy,
here i have the fix for the type error and i added a store of the value. I've tested it locally and there it works fine.
Pls test and comment if something is not fine. I will improve that. 
Kind Regards
> Fixed type read out of InteractionDataOption and added the value.

- src/main/java/com/mewna/catnip/cache/view/KolobokeLongEntityMap.java
- src/main/java/com/mewna/catnip/entity/builder/command/CommandOptionBuilder.java
- src/main/java/com/mewna/catnip/entity/builder/command/CommandOptionChoiceBuilder.java
- src/main/java/com/mewna/catnip/entity/builder/command/InteractionApplicationCommandCallbackDataBuilder.java
- src/main/java/com/mewna/catnip/entity/builder/command/InteractionResponseBuilder.java
- src/main/java/com/mewna/catnip/entity/builder/component/ActionRowBuilder.java
- src/main/java/com/mewna/catnip/entity/builder/component/ButtonBuilder.java
- src/main/java/com/mewna/catnip/entity/impl/EntityBuilder.java
- src/main/java/com/mewna/catnip/entity/impl/interaction/ApplicationCommandInteractionImpl.java
- src/main/java/com/mewna/catnip/entity/impl/interaction/ButtonInteractionImpl.java
- src/main/java/com/mewna/catnip/entity/impl/interaction/CustomIdInteractionDataImpl.java
- src/main/java/com/mewna/catnip/entity/impl/message/MessageImpl.java
- src/main/java/com/mewna/catnip/entity/impl/message/component/ActionRowImpl.java
- src/main/java/com/mewna/catnip/entity/impl/message/component/ButtonImpl.java
- src/main/java/com/mewna/catnip/entity/interaction/ApplicationCommandInteraction.java
- src/main/java/com/mewna/catnip/entity/interaction/ButtonInteraction.java
- src/main/java/com/mewna/catnip/entity/interaction/CustomIdInteractionData.java
- src/main/java/com/mewna/catnip/entity/interaction/InteractionType.java
- src/main/java/com/mewna/catnip/entity/message/Message.java
- src/main/java/com/mewna/catnip/entity/message/MessageOptions.java
- src/main/java/com/mewna/catnip/entity/message/component/ActionRow.java
- src/main/java/com/mewna/catnip/entity/message/component/Button.java
- src/main/java/com/mewna/catnip/entity/message/component/MessageComponent.java
- src/main/java/com/mewna/catnip/rest/Routes.java
- src/main/java/com/mewna/catnip/rest/handler/RestChannel.java
- src/main/java/com/mewna/catnip/rest/handler/RestInteraction.java
> feature: Message components

- src/main/java/com/mewna/catnip/entity/guild/GuildFeature.java
See https://github.com/discord/discord-api-docs/pull/3174
> Update Guild Feature Flags

- src/main/java/com/mewna/catnip/entity/guild/GuildFeature.java
Added further informations about when which feature is enabled
> Note boost tier for features

- src/main/java/com/mewna/catnip/entity/guild/GuildFeature.java
THREADS_ENABLED
THREADS_ENABLED_TESTING
> Add Features
