src/main/java/com/mewna/catnip/entity/impl/EntityBuilder.java
src/main/java/com/mewna/catnip/entity/user/Presence.java
src/main/java/com/mewna/catnip/shard/DispatchEmitter.java

- Fixes errors when activity type 3 (watching) is received
- Fixes errors when building a member object for GUILD_MEMBER_REMOVE events
- Fixes voice states sent with the GUILD_CREATE payloads not being cached due to missing `guild_id` field

fix a couple errors

---

src/main/java/com/mewna/catnip/util/pagination/AuditLogPaginator.java
src/main/java/com/mewna/catnip/util/pagination/BasePaginator.java
src/main/java/com/mewna/catnip/util/pagination/PaginationCallback.java

This allows the callback to stop paginating before the limit is reached

Add BasePaginator#fetchWhile

---

src/main/java/com/mewna/catnip/entity/channel/Channel.java
src/main/java/com/mewna/catnip/entity/channel/GuildChannel.java
src/main/java/com/mewna/catnip/entity/channel/MessageChannel.java
src/main/java/com/mewna/catnip/entity/channel/TextChannel.java
src/main/java/com/mewna/catnip/entity/channel/Webhook.java
src/main/java/com/mewna/catnip/entity/guild/Guild.java
src/main/java/com/mewna/catnip/entity/guild/Invite.java
src/main/java/com/mewna/catnip/entity/guild/Member.java
src/main/java/com/mewna/catnip/entity/message/Message.java
src/main/java/com/mewna/catnip/entity/user/User.java
src/main/java/com/mewna/catnip/rest/RestRequester.java
src/main/java/com/mewna/catnip/rest/handler/RestChannel.java
src/main/java/com/mewna/catnip/rest/handler/RestEmoji.java
src/main/java/com/mewna/catnip/rest/handler/RestGuild.java
src/main/java/com/mewna/catnip/rest/handler/RestInvite.java
src/main/java/com/mewna/catnip/rest/handler/RestUser.java
src/main/java/com/mewna/catnip/rest/handler/RestVoice.java
src/main/java/com/mewna/catnip/rest/handler/RestWebhook.java
src/main/java/com/mewna/catnip/util/pagination/BasePaginator.java

This is a *breaking* change, mainly because it removes the ability to use things like `#get()`. We still use CompletableFuture<T>s internally; it's just the external API that changed.

Convert CompletableFuture<T>s to CompletionStage<T>s

---

src/main/java/com/mewna/catnip/cache/MemoryEntityCache.java
src/main/java/com/mewna/catnip/internal/CatnipImpl.java
src/main/java/com/mewna/catnip/shard/manager/AbstractShardManager.java
src/main/java/com/mewna/catnip/shard/manager/DefaultShardManager.java
src/main/java/com/mewna/catnip/shard/manager/ShardCondition.java
src/main/java/com/mewna/catnip/shard/manager/ShardManager.java

Not ready to merge this, just gonna open it for @natanbc @SamOphis @gabixdev to give feedback on.
Fixes #85

Provide better shard management abstractions

---

src/main/java/com/mewna/catnip/cache/view/CacheView.java
src/main/java/com/mewna/catnip/cache/view/CompositeCacheView.java
src/main/java/com/mewna/catnip/cache/view/DefaultCacheView.java
src/main/java/com/mewna/catnip/cache/view/EmptyCacheView.java
src/main/java/com/mewna/catnip/cache/view/NamedCacheView.java
src/test/java/com/mewna/catnip/cache/view/CompositeCacheViewTests.java
src/test/java/com/mewna/catnip/cache/view/DefaultCacheViewTests.java
src/test/java/com/mewna/catnip/cache/view/DefaultNamedCacheViewTests.java

New methods:
- forEach
- isEmpty
- collect
- reduce
- anyMatch
- allMatch
- noneMatch
- min
- max
Fixes:
- mutable iterators/spliterators being returned by cache views

extra functions for cache views + tests

---

src/main/java/com/mewna/catnip/cache/MemoryEntityCache.java
src/main/java/com/mewna/catnip/cache/view/CompositeCacheView.java
src/main/java/com/mewna/catnip/cache/view/DefaultCacheView.java
src/main/java/com/mewna/catnip/cache/view/MutableCacheView.java
src/main/java/com/mewna/catnip/entity/impl/EntityBuilder.java
src/main/java/com/mewna/catnip/entity/message/Message.java
src/test/java/com/mewna/catnip/cache/view/CompositeCacheViewTests.java
src/test/java/com/mewna/catnip/cache/view/DefaultCacheViewTests.java
src/test/java/com/mewna/catnip/cache/view/DefaultNamedCacheViewTests.java

- optimize reduce, min, max implementations in CacheViews
- get rid of unneeded allocations in MemoryEntityCache
- fully replaced string keys with long keys for cache writes
- remove unneeded allocation in DefaultCacheView#snapshot()
- fix wrong parse method used in EntityBuilder (parseLong -> parseUnsignedLong)
- fix Message#channel() returning null on DMs (wrong cache key)

cache optimizations

---

src/main/java/com/mewna/catnip/Catnip.java
src/main/java/com/mewna/catnip/CatnipOptions.java
src/main/java/com/mewna/catnip/extension/AbstractExtension.java
src/main/java/com/mewna/catnip/internal/CatnipImpl.java
src/main/java/com/mewna/catnip/rest/handler/RestGuild.java
src/main/java/com/mewna/catnip/rest/handler/RestUser.java
src/main/java/com/mewna/catnip/rest/handler/RestWebhook.java
src/main/java/com/mewna/catnip/shard/CatnipShard.java
src/main/java/com/mewna/catnip/shard/DispatchEmitter.java
src/main/java/com/mewna/catnip/shard/event/AbstractDispatchManager.java
src/main/java/com/mewna/catnip/shard/event/DefaultDispatchManager.java
src/main/java/com/mewna/catnip/shard/event/DispatchManager.java
src/main/java/com/mewna/catnip/shard/manager/DefaultShardManager.java

- Added DispatchManager interface
- Responsible for creating MessageConsumer instances and dispatching events
- Useful to control how messages are sent across a cluster, eg only deliver them locally
- ShardManager is now responsible for the IDENTIFY backoff
- Easier to manage backoff across a cluster
- Raw rest methods don't take JSON objects as arguments anymore

Improve event dispatching, shard startup, raw rest methods

---

src/main/java/com/mewna/catnip/cache/EntityCache.java
src/main/java/com/mewna/catnip/cache/MemoryEntityCache.java
src/main/java/com/mewna/catnip/cache/NoopEntityCache.java
src/main/java/com/mewna/catnip/internal/CatnipImpl.java
src/main/java/com/mewna/catnip/shard/DispatchEmitter.java

Fixes #185 
Should the catnip.selfUser() method be nixed in favor of using catnip.cache().selfUser()?

Move SelfUser caching to EntityCache

---

src/main/java/com/mewna/catnip/entity/impl/AuditLogChangeImpl.java
src/main/java/com/mewna/catnip/entity/impl/ChannelPinsUpdateImpl.java
src/main/java/com/mewna/catnip/entity/impl/CreatedInviteImpl.java
src/main/java/com/mewna/catnip/entity/impl/EmbedImpl.java
src/main/java/com/mewna/catnip/entity/impl/GuildImpl.java
src/main/java/com/mewna/catnip/entity/impl/MemberImpl.java
src/main/java/com/mewna/catnip/entity/impl/MessageImpl.java

Jackson does not serialize fields when there is a method with the same name in the same class.
There is a workaround for this by adding the `@JsonProperty` annotation above of those variables
```- Added @JsonProperty Annotation to variables when there is a method with the exact same name in the sae class```

Fixed mewna/catnip#162

---

src/main/java/com/mewna/catnip/entity/util/Permission.java

Adds an String with the permission name on the Discord Client in the Permission Enum.

Add "readable descriptions" in Permission Enum

---

src/main/java/com/mewna/catnip/cache/view/CompositeCacheView.java

There is already no ordering, so there's no reason to use a list

Use HashSet instead of ArrayList to remove duplicates

---

src/main/java/com/mewna/catnip/rest/ResponseException.java
src/main/java/com/mewna/catnip/rest/handler/RestGuild.java
src/main/java/com/mewna/catnip/rest/requester/AbstractRequester.java

__***yes this is tested***__
but nah fr, this is tested and should close #231 (except for the fact that i can't reproduce the 400 bad request)
it wasn't my code causing the issues either which is a first. now any response code which is not 429 or 400 creates a neatly-formatted `ResponseException` which you can respond to by using `CompletionStage#exceptionally`.
i'd recommend creating a new tag for this as `0.13.3` is effectively broken when dealing with audit logs

fix audit logs and introduce actual http errors instead of only handling 400's

---

.circleci/config.yml
.idea/codeStyles/Project.xml
src/main/java/com/mewna/catnip/util/SafeVertxCompletableFuture.java

Even though we're getting rid of vertx, this class can still be used to protect whatever event loop we use

cleanup SafeVertxCompletableFuture

---

src/main/java/com/mewna/catnip/entity/message/Message.java

Innocent users could still be trolled using the rick roll if the troller used https://youtu.be/dQw4w9WgXcQ instead of https://www.youtube.com/watch?v=dQw4w9WgXcQ.
This commit fixes that

Adding youtu.be to the meme

---

.idea/codeStyles/Project.xml
src/main/java/com/mewna/catnip/entity/channel/Channel.java
src/main/java/com/mewna/catnip/entity/channel/NewsChannel.java
src/main/java/com/mewna/catnip/entity/channel/StoreChannel.java
src/main/java/com/mewna/catnip/entity/channel/TextChannel.java
src/main/java/com/mewna/catnip/entity/impl/EntityBuilder.java
src/main/java/com/mewna/catnip/entity/impl/NewsChannelImpl.java
src/main/java/com/mewna/catnip/entity/impl/StoreChannelImpl.java

Will close #267 
A couple things to consider before merging:
- Do we REALLY need the new `NewsChannel` type? We could probably get away with just an `isNews()` and `TextChannel` returning the right thing for type / ratelimits
- Does the default in-memory cache handle this right? How can we even test this?
- How will we handle store channels (type 6)?

Initial implementation of new channel types

---

src/main/java/com/mewna/catnip/entity/guild/Guild.java

Normally it is possible to ban users by their id without them being on
the server, fixed this in the default helper method.

Fix banning in guild entity, banning without being member

---

README.md
pom.xml
src/main/java/com/mewna/catnip/Catnip.java

It has been argued that catnip doesn't really count as reactive, and after looking things over, I honestly have to agree with this. This PR is made to make catnip actually properly reactive like it was supposed to be since the beginning. Rx2 is used here because vert.x's support for reactive-streams is terrible it seems :(
This PR would lead to calling catnip a "fully-async, *optionally-reactive*" library.
To explore in a future PR:
- Add a proxy or something to wrap REST calls in `Observable` variants
- Make the ratelimiter actually use Rx internally

Add basic Rx2 support

---

src/main/java/com/mewna/catnip/entity/channel/Category.java
src/main/java/com/mewna/catnip/entity/channel/GroupDMChannel.java
src/main/java/com/mewna/catnip/entity/channel/TextChannel.java
src/main/java/com/mewna/catnip/entity/channel/UserDMChannel.java
src/main/java/com/mewna/catnip/entity/channel/VoiceChannel.java
src/main/java/com/mewna/catnip/entity/impl/CategoryImpl.java
src/main/java/com/mewna/catnip/entity/impl/GroupDMChannelImpl.java
src/main/java/com/mewna/catnip/entity/impl/NewsChannelImpl.java
src/main/java/com/mewna/catnip/entity/impl/StoreChannelImpl.java
src/main/java/com/mewna/catnip/entity/impl/TextChannelImpl.java
src/main/java/com/mewna/catnip/entity/impl/UserDMChannelImpl.java
src/main/java/com/mewna/catnip/entity/impl/VoiceChannelImpl.java

Just adds the `type` field to channel entities. Will close #318.

Include channel type in serialized entity data

---

src/main/java/com/mewna/catnip/entity/channel/Channel.java

A little method which allows to check if a guild channel can accept messages.

Add Channel#isGuildMessageChannel utility method

---

src/main/java/com/mewna/catnip/extension/Extension.java
src/main/java/com/mewna/catnip/extension/hook/CatnipHook.java
src/main/java/com/mewna/catnip/shard/CatnipShardImpl.java
src/main/java/com/mewna/catnip/shard/ShardInfo.java
src/main/java/com/mewna/catnip/util/logging/DefaultLogAdapter.java

Added raw gateway open and close events to CatnipHook.
Extensions uses Unary Operator in place of Function with a fallback for extending classes
CatnipShard variables `id` and `total` and method `shardInfo()` replaced with shardInfo variable.
DefaultLogAdaptor#stackWalker no longer shows reflection frames, although this should never happen in practice regardless.

Extension, CatnipShard and LogAdaptor changes.

---

src/main/java/com/mewna/catnip/shard/CatnipShardImpl.java

Also, maybe remove properties as well? They aren't needed as per the API docs 
at <https://discordapp.com/developers/docs/topics/gateway#resume>.

Fixed Resume not being wrapped in {op,d}

---

.idea/codeStyles/Project.xml
.idea/inspectionProfiles/Real.xml
src/main/java/com/mewna/catnip/rest/Routes.java
src/main/java/com/mewna/catnip/rest/handler/RestChannel.java
src/main/java/com/mewna/catnip/rest/handler/RestEmoji.java
src/main/java/com/mewna/catnip/rest/handler/RestGuild.java
src/main/java/com/mewna/catnip/rest/handler/RestInvite.java
src/main/java/com/mewna/catnip/rest/handler/RestUser.java
src/main/java/com/mewna/catnip/rest/handler/RestWebhook.java

The reasoning behind this is that, while it's nice to have the routes follow the same format as the official docs, it's also a bit annoying to have `{}` in the parameters, as it makes things like using the route objects directly to make a REST proxy or similar a bit annoying. By changing to use `:params` instead, the routes become more in-line with what many common libraries/frameworks expect, and don't require any pre/post-processing in order to be usable (ex. because a library doesn't allow for `{}` in routes, or only uses `:params` for dynamic route params).

Convert routes to :params instead of {params}

---

src/main/java/com/mewna/catnip/entity/guild/Member.java
src/main/java/com/mewna/catnip/util/PermissionUtil.java

Before this PR, we were retrieving lowest role in hierarchy, because without specifying comparator in `Collections.sort()` underlying implementation will sort collection with natural order. This change implements ability to specify comparator that will be used while retrieving collection of ordered roles. This PR also fixes role hierarchy check that affects #340.

Fix role hierarchy check by using descending sort

---

README.md

Due to recent updating of the README file of `discordbotlist-stats`, the old URL will not redirect to the Catnip explanation part of the README anymore. This change fixes that.

Fixed link for Stats Extension

---

src/main/java/com/mewna/catnip/entity/guild/Guild.java
src/main/java/com/mewna/catnip/entity/util/Permission.java
src/test/java/com/mewna/catnip/permission/BitwiseTest.java

- Add missing "Video" (`STREAM`) permission
- Add missing "View Server Insights" (`VIEW_GUILD_INSIGHTS`) permission
- Change permName of `MENTION_EVERYONE` from `Mention Everyone` to `Mention @everyone, @here and All Roles` to match up with the name in the Discord client
- Change permName of `VIEW_AUDIT_LOG` from `View Audit Logs` to `View Audit Log` to match up with the name in the Discord client
- Change enum names of `MANAGE_NICKNAME` to `MANAGE_NICKNAMES`, as well as `MANAGE_EMOJI` to `MANAGE_EMOJIS` and `USE_EXTERNAL_EMOJI` to `USE_EXTERNAL_EMOJIS` to match up with the Discord documentation at https://discordapp.com/developers/docs/topics/permissions
- Move `PRIORITY_SPEAKER` further up to make the Permission enum match up with the list provided by the already mentioned Discord …

Add missing "Video" permission & general changes
